### ISSUE TITLE
Cant make a "delayed" render for a custom element 

### ISSUE THREAD

**Issue by fbrau** [nitrogen/nitrogen_core#106]
Hi. I have seen several web frameworks (css/js), -and I'm using one- that require
to declare some content out of the "structural" html. For example (real):

 
A dropdown:
`
 <nav>
    <a class=button data-target='#mytarget' ...>...</a>
  </nav>
`
 
We dont want to mess with the nav structure neither is necessary to render them together
so for this very dropdown I have to declare the dropdown contents after the nav:

`
<nav>... </nav>
 <div id=mytarget>... </div>
`
 
I'm not very proficient with nitrogen yet and I'm struggling to make this work.
At first I thought to initialize a comet handler when the page 'main' and
in the element's 'render_element()' to send the delayed content. That didn't 
work because messages sent from 'render_element()' went to a non existent
apparently, for example, wf:send(delayed_contents, {push,Dropdown}), event thought a did a comet initialization in the page's main(). My idea was then to do a wf:send(draw_delayed_contents)
somewhere after page load, but that seems tricky, that content should be there before 
the page 'onLoad' not after.

Now I'm thinking of storing that 'delayed' content in page state when preparing the render in
'render_element()'...

What could be a elegant way to make this happen -not that the pool concept is not- ?

**Comment by choptastic** [comment]
Hello,

To see if I understand this correctly, you're trying to put a placeholder element (say an empty div) on the page, then after the page loads, dynamically load the content for the div (in your example, adding a dropdown box to it).
 
I'm assuming the content of this information that's being loaded will vary from user to user (otherwise, you could load the same content every time).

The way I'd deal with this would be something like the following in your element definition.

```erlang
-module(my_delayed_element).
-compile(export_all).

transform_element(E) ->
   ...
   ID = E#my_delayed.id,
   wf:defer(#event{postback={load_delayed, ID}, delegate=?MODULE}),
   #panel{id=ID}.

event({load_delayed, ID}) ->
    Mod = wf:page_module(),
    Data = Mod:load_delayed(ID),
    wf:update(ID, Data).
```

Then in your page module, you can simply render your element with:

```erlang
#my_delayed{id=menu}
```

And later in your page module add:

```erlang
load_delayed(ID) ->
   my_custom_contents_for_the_named_id(ID).
``` 

That `load_delayed/1` function will then return whatever contents you want placed inside the element.  This will be done immediately after page load.
