### ISSUE TITLE
BUG removing an input widget that produced validation messages

### ISSUE THREAD

**Issue by fbrau** [nitrogen/nitrogen_core#113]
say I have a textbox. I click the [save] button. That produces a #is_required{} validation error, for example.

![captura de pantalla_2018-01-25_15-02-23](https://user-images.githubusercontent.com/8375315/35404147-38525bcc-0202-11e8-8cfe-3240aa207d60.png)

Now If we do a wf:remove(textbox), we leave the message behind with no way to remove it.

![captura de pantalla_2018-01-25_15-03-11](https://user-images.githubusercontent.com/8375315/35404169-4f163a72-0202-11e8-8939-1b4e598432b6.png)

I propose to modify nitrogen.js here:

NitrogenClass.prototype.$remove = function(anchor, path) {
    objs(path, anchor).remove();
}

for

NitrogenClass.prototype.$remove=function(a,b){
        x = objs(b,a);
        $(x).next('.LV_validation_message').remove();
        x.remove();
};

I tried it, it works and doesn't leave garbage behing.

**Comment by choptastic** [comment]
I like it! Great suggestion!

I'd you want to add that as a pull request, I will merge it.

On Jan 25, 2018 12:06 PM, "fbrau" <notifications@github.com> wrote:

say I have a textbox. I click the [save] button. That produces a
#is_required{} validation error, for example.

[image: captura de pantalla_2018-01-25_15-02-23]
<https://user-images.githubusercontent.com/8375315/35404147-38525bcc-0202-11e8-8cfe-3240aa207d60.png>

Now If we do a wf:remove(textbox), we leave the message behind with no way
to remove it.

[image: captura de pantalla_2018-01-25_15-03-11]
<https://user-images.githubusercontent.com/8375315/35404169-4f163a72-0202-11e8-8939-1b4e598432b6.png>

I propose to modify nitrogen.js here:

NitrogenClass.prototype.$remove = function(anchor, path) {
objs(path, anchor).remove();
}

for

NitrogenClass.prototype.$remove=function(a,b){
x = objs(b,a);
$(x).next('.LV_validation_message').remove();
x.remove();
};

I tried it, it works and doesn't leave garbage behing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nitrogen/nitrogen_core/issues/113>, or mute the thread

**Comment by fbrau** [comment]
I can do it. but I dont have the program that generates minified js files.

I you dont mind I will change nitrogen.js and nitrogen.min.js by hand, is that alright?

Btw, do you remember I posted that the last merge broke sync? I'll do my changes against the previous
commit. Does github understand that kind of pull requests?

**Comment by choptastic** [comment]
Absolutely!

I'm happy to minify then for you. But I like contributors to have their
names in the commits of only for credit-where-credit-is-due.
